---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
