---
site_name: My Story
site_url: https://shivan-s.github.io/my-story
nav:
  - Home: index.md
  - Chapter 1: 1.md
theme:
  name: material
  palette:
    - media: "(prefers-color-schema: dark)"
      scheme: slate
      primary: blue-grey
      accent: orange
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
    - media: "(prefers-color-schema: light)"
      scheme: default
      primary: grey
      accent: deep-orange
      toggle:
        icon: material/eye
        name: Switch to dark mode
watch:
  - docs
plugins:
  - search
